### ISSUE TITLE
Просит установить "gulp-plumber"

### ISSUE THREAD

**Issue by veremey** [coderiver/gulp#1]
Просит установить "gulp-plumber", "gulp-jade" так как его нету в package.json - добавьте пожалуйста. 
Когда закомментировать gulp/tasks/jade.js - все работает отлично. 
Как  по мне, сборка была бы быстрее, если добавить в "Дефолтную" таску - "Билд", чтобы одной командой проэкт и собрать и сразу запустить. 

Спасибо.

**Comment by akella** [comment]
Этот таск по умолчанию отключен - чтобы работал нужно устанавливать эти плагины да.
