### ISSUE TITLE
copy task

### ISSUE THREAD

**Issue by veremey** [coderiver/gulp#2]
если в папку src/img/somePath/ положить рисунок в каталог dist//img/somePath/ он не скопируется, для этого нужно поправить код:
`gulp.watch(config.src.img+'*', ['copy']);`
 на
 `gulp.watch(config.src.img+'**/*.*', ['copy']);`
 [ЗДЕСЬ](https://github.com/coderiver/gulp/blob/master/gulp/tasks/copy.js)

**Comment by Splintex** [comment]
Обновите шаблон! У вас очень старая версия.
